name: Main workflow

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            janestreet-bleeding: https://ocaml.janestreet.com/opam-repository
      
      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune 
      
      - name: Build artifact
        uses: actions/upload-artifact@v2
        with:
          name: _build
          path: _build
